spring:
  datasource:
    dynamic:
      datasource:
        mysql:
          driver-class-name: com.mysql.cj.jdbc.Driver # com.mysql.jdbc.Driver
          druid:
            validation-query: select 1
          password: 12345678
          url: jdbc:mysql://localhost:3306/reststyle?serverTimezone=UTC
          username: root
      #  oracle:
      #    driver-class-name: oracle.jdbc.driver.OracleDriver
      #    druid:
      #      validation-query: select * from dual
      #    password: HLHTCDA
      #    url: jdbc:oracle:thin:@localhost:1521/orcl
      #    username: HLHTCDA
      primary: mysql
      strict: false
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl